#!/bin/sh
#
# get_users: populate the users
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

oauth="$(cat oauth)"
since=$(sqlite3 ./users "select id from users order by id desc limit 1")

while true; do
	printf "\033[1mrequesting\033[0m https://api.github.com/users?since=${since}\n"
	data=$(curl -H "Authorization: token ${oauth}" -sSL "https://api.github.com/users?since=${since}&per_page=100") || exit 1

	users=$(echo "${data}" | jq "map(.login)")
	users=${users##[}
	users=${users%%]}

	since=$(echo $data | jq ".[-1].id")

	echo "${users}" | while IFS=",\n" read user; do
		[ -z "${user}" ] && continue
		name=${user#  \"}
		name=${name%\",}
		name=${name%%\"}

		id=$(echo ${data} | jq ".[] | select(.login==\"${name}\") | .id")

		printf "\r\033[1minserting\033[0m '${name}' of id '${id}'"
		sqlite3 ./users "insert into users values ( \"${name}\", \"\", ${id}, \"\" );"
	done

	clear && printf "\033[1A"
done
