#!/bin/sh
#
# get_stats - get last id of users
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

main() {
	printf "\033[1mnumber of users:\033[0m "
	sqlite3 ./users "select count(id) from users;"
}

main "$@"

